// Detailed Technical Specifications for Each Model

export interface ModelSpec {
  id: string
  name: string
  badge: string
  price: string
  dp: string
  monthly: string
  range: string
  battery: string
  motor: string
  maxSpeed: string
  charging: string
  superCharge?: string
  features: string[]
  whatsappLink: string
  gradient: string // Deprecated - use badgeColor instead
  badgeColor: string // Solid color for badge
  // Additional specs
  acceleration?: string
  braking?: string
  suspension?: string
  tire?: string
  groundClearance?: string
  weight?: string
  warranty?: string
  // Extended version
  hasExtended?: boolean
  extendedId?: string
}

export const MODEL_SPECS: ModelSpec[] = [
  {
    id: 'edpower',
    name: 'EdPower',
    badge: 'Premium',
    price: 'Rp 45,900,000',
    dp: 'Rp 10,000,000',
    monthly: 'Rp 1,200,000',
    range: '160 km',
    battery: '66Ah LFP',
    motor: 'BLDC 3kW',
    maxSpeed: '80 km/h',
    charging: '4 jam (0-100%), SuperCharge 15 menit (10-80%)',
    superCharge: '15 menit (10-80%)',
    acceleration: 'Smooth pickup, 3 riding modes',
    braking: 'Regenerative + Disc brake',
    suspension: 'Mono shock rear',
    tire: '80/90-14 (tubeless)',
    groundClearance: '190mm',
    weight: 'Optimized untuk performance',
    warranty: '3 tahun battery, 2 tahun motor',
    features: [
      'SuperCharge 15 menit (10-80%)',
      'Range 160km per charge',
      'AppleCarPlay & Android Auto',
      'Smart connectivity & app control',
      'Real-time battery monitoring',
      'Lock/unlock dari smartphone',
      'Emergency SOS button',
      'Theft tracking & accident detection',
      'Voice control (Google Assistant/Siri)',
      'Music streaming integration',
    ],
    whatsappLink: 'edpower',
    gradient: 'from-cyan-500 to-blue-500',
    badgeColor: 'bg-cyan-500',
  },
  {
    id: 'athena',
    name: 'Athena',
    badge: 'Mid-Range',
    price: 'Rp 28,700,000',
    dp: 'Rp 6,000,000',
    monthly: 'Rp 700,000',
    range: '110 km',
    battery: '33Ah LFP',
    motor: 'BLDC 2.5kW',
    maxSpeed: '80 km/h',
    charging: '2.5 jam (0-100%)',
    acceleration: 'Smooth acceleration, 2 riding modes',
    braking: 'Regenerative + Disc brake',
    suspension: 'Mono shock rear',
    tire: '80/90-14 (tubeless)',
    groundClearance: '180mm',
    weight: 'Lightweight & agile',
    warranty: '3 tahun battery, 2 tahun motor',
    features: [
      'Range 110km per charge',
      'Fast charging 2.5 jam',
      'Smart connectivity features',
      'App control & monitoring',
      'Battery health tracking',
      'Eco & Power mode',
      'LED lighting system',
      'Digital dashboard',
      'USB charging port',
      'Comfortable ergonomics',
    ],
    whatsappLink: 'athena',
    gradient: 'from-purple-500 to-pink-500',
    badgeColor: 'bg-purple-500',
    hasExtended: true,
    extendedId: 'athena-extended',
  },
  {
    id: 'athena-extended',
    name: 'Athena Extended',
    badge: 'Mid-Range Extended',
    price: 'Rp 30,700,000',
    dp: 'Rp 7,200,000',
    monthly: 'Rp 900,000',
    range: '130 km',
    battery: '42Ah LFP',
    motor: 'BLDC 2.5kW',
    maxSpeed: '80 km/h',
    charging: '3 jam (0-100%)',
    acceleration: 'Smooth acceleration, 2 riding modes',
    braking: 'Regenerative + Disc brake',
    suspension: 'Mono shock rear',
    tire: '80/90-14 (tubeless)',
    groundClearance: '180mm',
    weight: 'Lightweight & agile',
    warranty: '3 tahun battery, 2 tahun motor',
    features: [
      'Range 130km per charge',
      'Extended battery capacity',
      'Fast charging 3 jam',
      'Smart connectivity features',
      'App control & monitoring',
      'Battery health tracking',
      'Eco & Power mode',
      'LED lighting system',
      'Digital dashboard',
      'USB charging port',
      'Comfortable ergonomics',
    ],
    whatsappLink: 'athena',
    gradient: 'from-purple-500 to-pink-500',
    badgeColor: 'bg-purple-500',
  },
  {
    id: 'victory',
    name: 'Victory',
    badge: 'Most Popular',
    price: 'Rp 28,400,000',
    dp: 'Rp 5,000,000',
    monthly: 'Rp 550,000',
    range: '110 km',
    battery: '33Ah LFP',
    motor: 'BLDC 3kW',
    maxSpeed: '80 km/h',
    charging: '2.5 jam (0-100%)',
    acceleration: 'Smooth acceleration, 2 riding modes',
    braking: 'Regenerative + Disc brake',
    suspension: 'Mono shock rear',
    tire: '80/90-14 (tubeless)',
    groundClearance: '180mm',
    weight: 'Lightweight & reliable',
    warranty: '3 tahun battery, 2 tahun motor',
    features: [
      'Range 110km per charge',
      'Fast charging 2.5 jam',
      'Reliable performance',
      'Affordable pricing',
      'Digital dashboard',
      'LED lighting',
      'Eco mode for efficiency',
      'Comfortable seating',
      'Student discount available',
      'Easy maintenance',
    ],
    whatsappLink: 'victory',
    gradient: 'from-orange-500 to-yellow-500',
    badgeColor: 'bg-orange-500',
    hasExtended: true,
    extendedId: 'victory-extended',
  },
  {
    id: 'victory-extended',
    name: 'Victory Extended',
    badge: 'Most Popular Extended',
    price: 'Rp 29,700,000',
    dp: 'Rp 7,400,000',
    monthly: 'Rp 950,000',
    range: '130 km',
    battery: '42Ah LFP',
    motor: 'BLDC 3kW',
    maxSpeed: '80 km/h',
    charging: '3 jam (0-100%)',
    acceleration: 'Smooth acceleration, 2 riding modes',
    braking: 'Regenerative + Disc brake',
    suspension: 'Mono shock rear',
    tire: '80/90-14 (tubeless)',
    groundClearance: '180mm',
    weight: 'Lightweight & reliable',
    warranty: '3 tahun battery, 2 tahun motor',
    features: [
      'Range 130km per charge',
      'Extended battery capacity',
      'Fast charging 3 jam',
      'Reliable performance',
      'Affordable pricing',
      'Digital dashboard',
      'LED lighting',
      'Eco mode for efficiency',
      'Comfortable seating',
      'Student discount available',
      'Easy maintenance',
    ],
    whatsappLink: 'victory',
    gradient: 'from-orange-500 to-yellow-500',
    badgeColor: 'bg-orange-500',
  },
  {
    id: 'bees',
    name: 'Bees',
    badge: 'Entry Level',
    price: 'Rp 15,900,000',
    dp: 'Rp 3,000,000',
    monthly: 'Rp 400,000',
    range: '80 km',
    battery: '25Ah LFP',
    motor: 'BLDC 1.2kW',
    maxSpeed: '55 km/h',
    charging: '2 jam (0-100%)',
    acceleration: 'Smooth & efficient',
    braking: 'Regenerative + Disc brake',
    suspension: 'Mono shock rear',
    tire: '70/90-14 (tubeless)',
    groundClearance: '170mm',
    weight: 'Compact & lightweight',
    warranty: '3 tahun battery, 2 tahun motor',
    features: [
      'Range 80km per charge',
      'Compact design',
      'Budget-friendly',
      'Perfect for city commuting',
      'Easy to park & maneuver',
      'Digital speedometer',
      'LED headlight',
      'USB charging port',
      'Student discount available',
      'Low maintenance cost',
    ],
    whatsappLink: 'bees',
    gradient: 'from-green-500 to-teal-500',
    badgeColor: 'bg-green-500',
  },
]
